
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author irpik
 */
public class Main extends javax.swing.JFrame {
    
    HaritaFrame haritaFrame = new HaritaFrame();
    Cizim cizim = new Cizim();
    DefaultListModel<String> cizimModel = new DefaultListModel<>();
    DefaultListModel<String> noktaModel = new DefaultListModel<>();
    DefaultListModel<String> poligonModel = new DefaultListModel<>();
    ArrayList<Integer> xArrayList=new ArrayList<Integer>();
    ArrayList<Integer> yArrayList=new ArrayList<Integer>();
    ArrayList<Integer> xCizgiArrayList=new ArrayList<Integer>();
    ArrayList<Integer> yCizgiArrayList=new ArrayList<Integer>();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setTitle("Veri Girişi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xBoyut = new javax.swing.JTextField();
        yBoyut = new javax.swing.JTextField();
        olustur = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        noktaXkoordinat = new javax.swing.JTextField();
        noktaYkoordinat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noktaEkle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        noktaListe = new javax.swing.JList<>();
        noktaCizimYap = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        noktaKalinlik = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cizgiXkoordinat = new javax.swing.JTextField();
        cizgiYkoordinat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cizgiEkle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cizgiListe = new javax.swing.JList<>();
        cizgiCizimYap = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cizigiKalinlik = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        poligonXkoordinat = new javax.swing.JTextField();
        poligonYkoordinat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        poligonTipi = new javax.swing.JComboBox<>();
        poligonEkle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        poligonListe = new javax.swing.JList<>();
        poligonCizimYap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 230, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Harita Boyutunu Giriniz:");

        xBoyut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xBoyutKeyTyped(evt);
            }
        });

        yBoyut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yBoyutKeyTyped(evt);
            }
        });

        olustur.setBackground(new java.awt.Color(255, 255, 0));
        olustur.setText("Oluştur");
        olustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olusturActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("x");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xBoyut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yBoyut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(olustur))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xBoyut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yBoyut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(olustur))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Nokta Oluştur:");

        noktaXkoordinat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noktaXkoordinatKeyTyped(evt);
            }
        });

        noktaYkoordinat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noktaYkoordinatKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("x");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("y");

        noktaEkle.setBackground(new java.awt.Color(0, 204, 0));
        noktaEkle.setText("Ekle");
        noktaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktaEkleActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(noktaListe);

        noktaCizimYap.setBackground(new java.awt.Color(255, 255, 0));
        noktaCizimYap.setText("Çizim Yap");
        noktaCizimYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktaCizimYapActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Kalınlık:");

        noktaKalinlik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Küçük", "Orta", "Büyük" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noktaKalinlik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noktaXkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noktaYkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noktaEkle)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(noktaCizimYap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noktaXkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noktaYkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noktaEkle))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noktaKalinlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(noktaCizimYap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Çizgi Oluştur:");

        cizgiXkoordinat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cizgiXkoordinatKeyTyped(evt);
            }
        });

        cizgiYkoordinat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cizgiYkoordinatKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("x");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("y");

        cizgiEkle.setBackground(new java.awt.Color(0, 204, 0));
        cizgiEkle.setText("Ekle");
        cizgiEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cizgiEkleActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(cizgiListe);

        cizgiCizimYap.setBackground(new java.awt.Color(255, 255, 0));
        cizgiCizimYap.setText("Çizim Yap");
        cizgiCizimYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cizgiCizimYapActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Kalınlık:");

        cizigiKalinlik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İnce", "Orta", "Kalın" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cizigiKalinlik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cizgiXkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cizgiYkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cizgiEkle)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cizgiCizimYap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cizgiXkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cizgiYkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cizgiEkle))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cizigiKalinlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(cizgiCizimYap)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Poligon Oluştur:");

        poligonXkoordinat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                poligonXkoordinatKeyTyped(evt);
            }
        });

        poligonYkoordinat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                poligonYkoordinatKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("x");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("y");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("İç Dizayn:");

        poligonTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boş", "Saydam", "Dolu" }));

        poligonEkle.setBackground(new java.awt.Color(0, 204, 0));
        poligonEkle.setText("Ekle");
        poligonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonEkleActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(poligonListe);

        poligonCizimYap.setBackground(new java.awt.Color(255, 255, 0));
        poligonCizimYap.setText("Çizim Yap");
        poligonCizimYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonCizimYapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poligonXkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poligonYkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poligonEkle))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poligonTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(poligonCizimYap)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poligonXkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poligonYkoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poligonEkle))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poligonTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(poligonCizimYap)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xBoyutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xBoyutKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_xBoyutKeyTyped

    private void yBoyutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yBoyutKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_yBoyutKeyTyped

    private void olusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olusturActionPerformed
        haritaFrame = new HaritaFrame();
        int xEkseni = Integer.valueOf(xBoyut.getText())+18;
        int yEkseni = Integer.valueOf(yBoyut.getText())+40;
        haritaFrame.setSize(xEkseni, yEkseni);
        haritaFrame.setVisible(true);
        haritaFrame.setResizable(false);
        
        //haritaFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_olusturActionPerformed

    private void noktaXkoordinatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noktaXkoordinatKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_noktaXkoordinatKeyTyped

    private void noktaYkoordinatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noktaYkoordinatKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_noktaYkoordinatKeyTyped

    private void cizgiXkoordinatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cizgiXkoordinatKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cizgiXkoordinatKeyTyped

    private void cizgiYkoordinatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cizgiYkoordinatKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cizgiYkoordinatKeyTyped

    private void poligonXkoordinatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_poligonXkoordinatKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_poligonXkoordinatKeyTyped

    private void poligonYkoordinatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_poligonYkoordinatKeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                ||(vchar == KeyEvent.VK_BACK_SPACE)
                ||(vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_poligonYkoordinatKeyTyped

    private void cizgiEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cizgiEkleActionPerformed
        int xKoordinat = Integer.valueOf(cizgiXkoordinat.getText());
        int yKoordinat = Integer.valueOf(cizgiYkoordinat.getText());
//        int kalin;
//        String kalinlik = cizigiKalinlik.getSelectedItem().toString();
//        if (kalinlik.equals("İnce")) {
//            kalin = 2;
//        }
//        else if (kalinlik.equals("Orta")) {
//            kalin = 5;
//        }
//        else{
//            kalin = 7;
//        }
//        Cizgi c = new Cizgi(xKoordinat, yKoordinat, kalin);
//        cizim.cizgiArrayList.add(c);
        xCizgiArrayList.add(xKoordinat);
        yCizgiArrayList.add(yKoordinat);
        String liste ="(" + xKoordinat + "," + yKoordinat + ")";  
        cizimModel.addElement(liste);
        cizgiListe.setModel(cizimModel);
    }//GEN-LAST:event_cizgiEkleActionPerformed

    private void cizgiCizimYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cizgiCizimYapActionPerformed
       
     
        int x[]=new int[xCizgiArrayList.size()];
        int i=0;
        for (Integer integer : xCizgiArrayList) {
            x[i]=integer;
            i++;
        }
        
        int y[]=new int[yCizgiArrayList.size()];
        i=0;
        for (Integer integer : yCizgiArrayList) {
            y[i]=integer;
            i++;
        }
        int kalin;
        String kalinlik = cizigiKalinlik.getSelectedItem().toString();
        if (kalinlik.equals("İnce")) {
            kalin = 2;
        }
        else if (kalinlik.equals("Orta")) {
            kalin = 5;
        }
        else{
            kalin = 7;
        }
        Cizgi c = new Cizgi(x, y, kalin);
        cizim.cizgiArrayList.add(c);
        
        
        haritaFrame.add(cizim);
        haritaFrame.setVisible(true);
        haritaFrame.repaint();
         
         xCizgiArrayList=new ArrayList<>();
         yCizgiArrayList=new ArrayList<>();
    }//GEN-LAST:event_cizgiCizimYapActionPerformed

    private void noktaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktaEkleActionPerformed
        int xKoordinat = Integer.valueOf(noktaXkoordinat.getText());
        int yKoordinat = Integer.valueOf(noktaYkoordinat.getText());
        int kalin;
        String kalinlik = noktaKalinlik.getSelectedItem().toString();
        if (kalinlik.equals("Küçük")) {
            kalin = 2;
        }
        else if (kalinlik.equals("Orta")) {
            kalin = 5;
        }
        else{
            kalin = 7;
        }
        Nokta n = new Nokta(xKoordinat, yKoordinat, kalin);
        cizim.noktaArrayList.add(n);
        String liste = "(" + xKoordinat + "," + yKoordinat + ")"; 
        noktaModel.addElement(liste);
        noktaListe.setModel(noktaModel);
    }//GEN-LAST:event_noktaEkleActionPerformed

    private void noktaCizimYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktaCizimYapActionPerformed
       
       haritaFrame.add(cizim);
       haritaFrame.setVisible(true);
       haritaFrame.repaint();
    }//GEN-LAST:event_noktaCizimYapActionPerformed

    private void poligonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonEkleActionPerformed
        int xKoordinat = Integer.valueOf(poligonXkoordinat.getText());
        int yKoordinat = Integer.valueOf(poligonYkoordinat.getText());
//        int secim;
//        String tip = poligonTipi.getSelectedItem().toString();
//        if (tip.equals("Boş")) {
//            secim = 1;
//        }
//        else if (tip.equals("Saydam")) {
//            secim = 2;
//        }
//        else{
//            secim = 3;
//        }
//        Poligon p = new Poligon(xKoordinat, yKoordinat, secim);
//        cizim.poligonArrayList.add(p);
        xArrayList.add(xKoordinat);
        yArrayList.add(yKoordinat);
        String liste = "(" + xKoordinat + "," + yKoordinat + ")"; 
        poligonModel.addElement(liste);
        poligonListe.setModel(poligonModel);
    }//GEN-LAST:event_poligonEkleActionPerformed

    private void poligonCizimYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonCizimYapActionPerformed
        
        
        int x[]=new int[xArrayList.size()];
        int i=0;
        for (Integer integer : xArrayList) {
            x[i]=integer;
            i++;
        }
        
        int y[]=new int[yArrayList.size()];
        i=0;
        for (Integer integer : yArrayList) {
            y[i]=integer;
            i++;
        }
        int secim;
        String tip = poligonTipi.getSelectedItem().toString();
        if (tip.equals("Boş")) {
            secim = 1;
        }
        else if (tip.equals("Saydam")) {
            secim = 2;
        }
        else{
            secim = 3;
        }
        Poligon p = new Poligon(x, y, secim);
        cizim.poligonArrayList.add(p);
        
        haritaFrame.add(cizim);
        haritaFrame.setVisible(true);
         haritaFrame.repaint();
         
         xArrayList=new ArrayList<>();
         yArrayList=new ArrayList<>();
    }//GEN-LAST:event_poligonCizimYapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cizgiCizimYap;
    private javax.swing.JButton cizgiEkle;
    private javax.swing.JList<String> cizgiListe;
    private javax.swing.JTextField cizgiXkoordinat;
    private javax.swing.JTextField cizgiYkoordinat;
    private javax.swing.JComboBox<String> cizigiKalinlik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton noktaCizimYap;
    private javax.swing.JButton noktaEkle;
    private javax.swing.JComboBox<String> noktaKalinlik;
    private javax.swing.JList<String> noktaListe;
    private javax.swing.JTextField noktaXkoordinat;
    private javax.swing.JTextField noktaYkoordinat;
    private javax.swing.JButton olustur;
    private javax.swing.JButton poligonCizimYap;
    private javax.swing.JButton poligonEkle;
    private javax.swing.JList<String> poligonListe;
    private javax.swing.JComboBox<String> poligonTipi;
    private javax.swing.JTextField poligonXkoordinat;
    private javax.swing.JTextField poligonYkoordinat;
    private javax.swing.JTextField xBoyut;
    private javax.swing.JTextField yBoyut;
    // End of variables declaration//GEN-END:variables
}
